### ISSUE TITLE
Create Project Structure

### ISSUE THREAD

**Issue by jessgreene** [elitatusc/Protohype#13]
**Create the structure of these classes:**
1. Create the Credentials class to connect to database via JDBC
2. Create the Client class to receive client requests 
3. Create the Server class to accept client requests
4. Create the Service class to provide the service to the client

**Comment by jessgreene** [comment]
Added Maven surefire plugin to the pom.xml file to allow the maven.yml file to run

**Comment by elitatusc** [comment]
Added the maven jar plugin to configure docker
