### ISSUE TITLE
Add Maven.yml file

### ISSUE THREAD

**Issue by morningfork** [elitatusc/Protohype#37]
1. Add Java continuous integration with Maven through maven.yml file

**Comment by jessgreene** [comment]
Tried to add the maven.yml file but failing on Build Maven

**Comment by jessgreene** [comment]
Added maven surefire plugin to pom.xml file

**Comment by jessgreene** [comment]
Removed the optinal dependency graph as this was causing the maven.yml file to fail

**Comment by jessgreene** [comment]
maven.yml file runs without any issues and has been pushed to the main branch
